apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-operator
  namespace: appdynamics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: appdynamics-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - resourcequotas
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups: 
  - "batch"
  - "extensions"
  resources: 
  - "jobs"
  verbs: 
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appdynamics.com
  resources:
  - '*'
  - clusteragents
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-operator
subjects:
- kind: ServiceAccount
  name: appdynamics-operator
  namespace: appdynamics
roleRef:
  kind: ClusterRole
  name: appdynamics-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: appd-cluster-agent
  namespace: appdynamics
spec: 
  replicas: 1
  template: 
    metadata: 
      annotations: 
        appd-agent-id: appdynamics-cluster-agent
      labels: 
        name: cluster-agent-config
    spec: 
      restartPolicy: Always
      containers: 
        - env: 
            - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
              valueFrom: 
                secretKeyRef: 
                  key: controller-key
                  name: cluster-agent-secret
            - name: APPDYNAMICS_EVENT_ACCESS_KEY
              valueFrom: 
                secretKeyRef: 
                  key: event-key
                  name: cluster-agent-secret
            - name: APPDYNAMICS_REST_API_CREDENTIALS
              valueFrom: 
                secretKeyRef: 
                  key: api-user
                  name: cluster-agent-secret
            - name: APPDYNAMICS_AGENT_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
          image: "docker.io/appdynamics/cluster-agent:latest"
          imagePullPolicy: IfNotPresent
          name: cluster-agent
          ports: 
            - containerPort: 8989
              protocol: TCP
          resources: 
            limits: 
              cpu: 200m
              memory: 300M
            requests: 
              cpu: 100m
              memory: 100M
          volumeMounts: 
            - mountPath: /opt/appdynamics/config/
              name: agent-config
      serviceAccountName: appdynamics-operator
      volumes: 
        - configMap: 
            name: cluster-agent-config
          name: agent-config

